<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
	<title><?= $this->pageTitle ?> - <?= $this->application_name ?></title>
	<link href="/css/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="/css/print.css" media="print" rel="stylesheet" type="text/css" />
	<!--[if lt IE 8]>
		<link href="/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<![endif]-->
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
</head>
<body class="bp">
	<div id="header">
		<div class="container">
			<div class="span-1">&nbsp;</div>
			<div class="span-22">
				<h1><?= $this->application_name ?></h1>
			</div>
			<div class="span-1 last">&nbsp;</div>
		</div>
	</div>
	<div id="container">
		<div class="container">
			<div class="span-1">&nbsp;</div>
			<div class="span-22">
				<?= $this->layout()->content ?>
			</div>
			<div class="span-1 last">&nbsp;</div>
		</div>
	</div>
	<div id="footer">
	</div>
</body>
</html>
