<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
	<title><?= $this->pageTitle ?> - <?= $this->application_name ?></title>
	<link href="/css/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<link href="/css/print.css" media="print" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/themes/flick/jquery-ui.css" type="text/css"/> 
	<link rel="stylesheet" href="/library/uniform/css/uniform.default.css" type="text/css"/> 

	<!--[if lt IE 8]>
		<link href="/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<![endif]-->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/library/uniform/jquery.uniform.min.js"></script>
	<script type="text/javascript" src="/js/storebot.js"></script>
	<script type="text/javascript">
	var sb = window.sb || {};
	</script>
</head>
<body class="bp">
	<div id="top-stripe">&nbsp;</div>
	<div class="hide" id="flash-message"></div>
	<div id="header">
		<div class="container">
			<div class="span-1">&nbsp;</div>
			<div id="header-image" class="span-7">
				<img src="/images/logo.png" />
			</div>
			<div class="span-1">&nbsp;</div>
			<div id="top-nav" class="span-14">
				<a href="/about"><img class="tab" src="/images/about_tab<?= $this->controller == 'index' && $this->action == 'about' ? '_active' : '' ?>.png" /></a>
				<a href="/shop"><img class="tab" src="/images/shop_tab<?= $this->controller == 'shop' ? '_active' : '' ?>.png" /></a>
				<a href="/policies"><img class="tab" src="/images/policies_tab<?= $this->controller == 'index' && $this->action == 'policies' ? '_active' : '' ?>.png" /></a>
				<a href="/cart"><img class="cart" src="/images/cart_tab<?= $this->controller == 'cart' ? '_active' : '' ?>.png" /></a>
			</div>
			<div class="span-1 last">&nbsp;</div>
		</div>
	</div>
	<div id="main">
		<div class="container">
			<div class="span-1">&nbsp;</div>
			<div id="content-background" class="span-22">
				<div class="span-1">&nbsp;</div>
				<div id="content" class="span-20">
					<?= $this->layout()->content ?>
				</div>
				<div class="span-1">&nbsp;</div>
				&nbsp;
			</div>
			<div class="span-1 last">&nbsp;</div>
		</div>
	</div>
	<div id="footer">
		<div class="container">
			<div class="span-1">&nbsp;</div>
			<div id="footer-background" class="span-22">
				<a href="/contact">Contact</a>
				<a href="http://blog.swap-bot.com/">Blog</a>
				<a href="http://www.swap-bot.com/">Go To Swap-Bot.com</a>
			</div>
			<div class="span-1 last">&nbsp;</div>
		</div>
	</div>
</body>
</html>
