<?= $this->render('shop/_navigation.phtml') ?>
<div class="span-15 last">
	<div class="span-10">
		<h2><?= $this->product['name'] ?></h2>
		<div>
			<?= $this->product['description'] ?>
		</div>
	</div>
	<div class="span-5 last">
		<select name="item">
		<?php foreach ($this->product['items'] as $item) : ?>
		<option value="<?= $item['id'] ?>"><?= $item['name'] ?> - $<?= $item['price'] ?></option>
		<?php endforeach ?>
		</select>
	</div>
</div>
