<?= $this->render('shop/_navigation.phtml') ?>
<div class="span-15 last">
	<div class="span-10">
		<h2><?= $this->product['name'] ?></h2>
		<div>
			<?= $this->product['description'] ?>
		</div>
	</div>
	<div class="span-5 last">
		<select id="chosen-item" name="item">
		<?php foreach ($this->product['items'] as $item) : ?>
		<option value="<?= $item['id'] ?>"><?= $item['name'] ?> - $<?= $item['price'] ?></option>
		<?php endforeach ?>
		</select><br />
		quatity: <input type="text" size="3" name="quatity" id="quantity" value="1" />
		<input type="button" id="add-to-cart" value="Add to cart" />
	</div>
</div>

<script type="text/javascript">
sb.product = <?= json_encode($this->product) ?>;

$(function() {
	$("#add-to-cart").click(function() {
		var item_id = $("#chosen-item").val();
		var quantity = $("#quantity").val();

		var post = {
			product_id: sb.product.id,
			item_id: item_id,
			quantity: quantity
		};
		$.post('/cart/add-to-cart', post, function(data) {
		}, 'json');
	});
});
</script>
