<form action="<?= $this->type == 'add' ? '/admin/add-product' : '/admin/update-product' ?>" method="post">
<?php if ($this->type == 'update') : ?>
<input type="hidden" name="product[id]" value="<?= $this->product['id'] ?>" />
<?php endif ?>
<?php if ($this->type == 'update') : ?>
<h2>Update <?= $this->product['name'] ?></h2>
<a href="/shop/<?= $this->product['slug'] ?>">View <?= $this->product['name'] ?> Page </a>
<?php else : ?>
<h2>Add new Product</h2>
<?php endif ?>
<table>
	<tr>
		<td>Name:</td>
		<td><input type="text" name="product[name]" size="70" value="<?= $this->type == 'update' ? $this->product['name'] : '' ?>" /></td>
	</tr>
	<tr>
		<td>Slug:</td>
		<td><input type="text" name="product[slug]" size="70" value="<?= $this->type == 'update' ? $this->product['slug'] : '' ?>" /></td>
	</tr>
	<tr>
		<td>Category:</td>
		<td>
			<select name="product[category_id]">
			<?php foreach ($this->categories as $category) : ?>
			<option <?= $this->type == 'update' && $this->product['category_id'] == $category['id'] ? 'selected="selected"' : '' ?> value="<?= $category['id'] ?>"><?= $category['name'] ?></option>
			<?php endforeach ?>
			</select>
		</td>
	</tr>
	<?php if ($this->type == 'update') : ?>
	<tr>
		<td>&nbsp;</td>
		<td><a href="#" id="manage-images">Manage images</a></td>
	</tr>
	<?php endif ?>
	<tr>
		<td>Description:</td>
		<td>
			<textarea name="product[description]" rows="10" cols="40"><?= $this->type == 'update' ? $this->product['description'] : '' ?></textarea>
		</td>
	</tr>
	<tr>
		<td style="vertical-align: top">Items:</td>
		<td>
			<table id="item-table">
				<thead>
				<tr><td>Name</td><td>Price</td><td>Quantity</td></tr>
				</thead>
				<tbody>
				<?php if ($this->type == 'update') : ?>
				<?php foreach ($this->product['items'] as $item) : ?>
				<tr>
					<td><input type="text" name="item[<?= $item['id'] ?>][name]" value="<?= $item['name'] ?>" /></td>
					<td><input type="text" name="item[<?= $item['id'] ?>][price]" value="<?= $item['price'] ?>" /></td>
					<td><input type="text" name="item[<?= $item['id'] ?>][quantity]" value="<?= $item['quantity'] ?>" /></td>
					<td><input type="checkbox" name="item[<?= $item['id'] ?>][delete]" value="1" /> Delete</td>
				</tr>
				<?php endforeach ?>
				<?php endif ?>
				<tr class="newitem">
					<td><input type="text" name="newitem[0][name]" /></td>
					<td><input type="text" name="newitem[0][price]" /></td>
					<td><input type="text" name="newitem[0][quantity]" /></td>
					<td><a href="#" id="add-another-item">Add another</a></td>
				</tr>
				</tbody>
			</table>
		</td>
	</tr>
	<tr>
		<td><input type="submit" value="<?= $this->type == 'add' ? 'Add' : 'Update' ?>" /></td>
	</tr>
</table>
</form>

<script type="text/javascript" src="/js/ajaxupload.js"></script>
<script type='text/javascript'>
$(function() {
	$("#add-another-item").click(function(e) {
		e.preventDefault();
		var count = $("#item-table tbody tr.newitem").length;
		$("#item-table tbody").append('<tr class="newitem"><td><input type="text" name="newitem[' + count + '][name]" /></td><td><input type="text" name="newitem[' + count + '][price]" /></td><td><input type="text" name="newitem[' + count + '][quantity]" /></td><td>&nbsp;</td></tr>');
	});

	$("#manage-images").click(function(e) {
		e.preventDefault();
		$("#manage-images-dialog").dialog('open');
	});

	$("#manage-images-dialog").dialog({
		autoOpen: false,
		height: 300,
		width: 650,
		modal: true,
		buttons: {
			'OK': function() {
				$(this).dialog('close');
			}
		},
		close: function() {
		}
	});

	var status=$('#upload-status');
	new AjaxUpload($('#choose-upload'), {
		action: '/admin/upload-product-image',
		name: 'image',
		onSubmit: function(file, ext){
			if (! (ext && /^(jpg|png|jpeg|gif)$/i.test(ext))){
                  // check for valid file extension
				status.text('Only JPG, PNG or GIF files are allowed');
				return false;
			}
			status.text('Uploading...');
		},
		onComplete: function(file, response){
			//On completion clear the status
			status.text('');
			//Add uploaded file to list
			if(response==="success"){
				$('<li></li>').appendTo('#files').html('<img src="./uploads/'+file+'" alt="" /><br />'+file).addClass('success');
			} else{
				$('<li></li>').appendTo('#files').text(file).addClass('error');
			}
		}
	})
});
</script>

<div id="manage-images-dialog" title="Manage Images">
	<div id="upload-status"></div>
	<input type='radio' name="image_type" value="small" checked="checked" /> Small
	<input type='radio' name="image_type" value="medium" /> Medium
	<input type='radio' name="image_type" value="large" /> Large
	<input type="button" value="Choose image..." id="choose-upload" />
</div>
